# Generated by Django 4.2.7 on 2024-03-08 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='SharedAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_edit', models.DateTimeField()),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.note')),
                ('shared_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_access_notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='users_with_edit_access',
            field=models.ManyToManyField(related_name='edit_access_notes', through='users.SharedAccess', to=settings.AUTH_USER_MODEL),
        ),
    ]
